### ISSUE TITLE
Script Bugs with Image based on Debian 9 stretch

### ISSUE THREAD

**Issue by abdennour** [renatomefi/php-fpm-healthcheck#40]
# Environment: 

```sh
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/
```
# How to reproduce : 

Run `php-fpm-healthcheck --listen-queue=10 `
And you will get this error : 

```
/usr/local/bin/php-fpm-healthcheck: 78: test: Illegal number:
```

**Comment by wandersonwhcr** [comment]
Hello @abdennour sorry for the delay (almost 2 years)

I think this issue was resolved: I created a test to verify this behavior and it passed.

https://github.com/renatomefi/php-fpm-healthcheck/actions/runs/1698343482

Do you remember how can we reproduce this problem?

TY

**Comment by abdennour** [comment]
شكرا @wandersonwhcr

**Comment by mnpenner** [comment]
I'm still seeing this error.

```
# php-fpm-healthcheck --verbose; echo $?
Trying to connect to php-fpm via: /var/run/php-fpm.sock/status
php-fpm status output:

0
```

Works fine, but:

```
# php-fpm-healthcheck --verbose --listen-queue=10; echo $?
Trying to connect to php-fpm via: /var/run/php-fpm.sock/status
php-fpm status output:

'listen queue' value '' and expected is less than '10'
/usr/local/bin/php-fpm-healthcheck: 78: test: Illegal number:
0
```

Status is still coming out 0 interestingly enough.

Running on `Debian GNU/Linux 10 (buster)` in Kubernetes.

**Edit:** Nevermind. I missed the [bit about `pm.status_path`](https://github.com/renatomefi/php-fpm-healthcheck#enable-php-fpm-status-page).
